/**
 * Extracts the curated icon set out of Font Awesome Free into `src/icon-paths.ts`.
 *
 * Why a generator rather than the package itself: importing the Font Awesome CSS pulls a
 * ~400 KB webfont for ten glyphs, and importing the SVG-core packages puts a runtime
 * dependency in the bundle for data that never changes. Extracting the path data at
 * development time gives ten strings, no font, no runtime dependency, and — because the set
 * is a literal object — no way to reference an icon that is not in it.
 *
 * `icon-paths.spec.ts` re-runs this extraction and fails if the committed file drifts, so an
 * upgrade to Font Awesome cannot silently change a glyph.
 *
 * Font Awesome Free icons are CC BY 4.0 (https://fontawesome.com/license/free); the
 * attribution is carried in the generated file.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** name in our code → `<style>/<file>` in the Font Awesome package. */
export const WANTED: Record<string, string> = {
  calendar: 'regular/calendar',
  clock: 'regular/clock',
  user: 'solid/user',
  scissors: 'solid/scissors',
  check: 'solid/check',
  xmark: 'solid/xmark',
  spinner: 'solid/spinner',
  'triangle-exclamation': 'solid/triangle-exclamation',
  'credit-card': 'solid/credit-card',
  whatsapp: 'brands/whatsapp',
};

export interface IconData {
  viewBox: string;
  path: string;
}

const packageDir = dirname(fileURLToPath(import.meta.url));

/** Where the package keeps its SVGs. Resolved through the module graph, not guessed. */
function svgPath(file: string): string {
  const root = resolve(packageDir, '../node_modules/@fortawesome/fontawesome-free/svgs');

  return resolve(root, `${file}.svg`);
}

/**
 * Pull the viewBox and the single path out of one Font Awesome SVG.
 *
 * Throws rather than returning a partial icon: a missing path would render an empty square,
 * which is harder to notice than a failed build.
 */
export function extract(file: string): IconData {
  const svg = readFileSync(svgPath(file), 'utf8');

  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
  const path = /\sd="([^"]+)"/.exec(svg)?.[1];

  if (viewBox === undefined || path === undefined) {
    throw new Error(`${file}.svg has no viewBox or no path`);
  }

  return { viewBox, path };
}

export function buildAll(): Record<string, IconData> {
  return Object.fromEntries(Object.entries(WANTED).map(([name, file]) => [name, extract(file)]));
}

/** The exact text of the generated module, so the drift test can compare strings. */
export function render(icons: Record<string, IconData>): string {
  const entries = Object.entries(icons)
    .map(
      ([name, data]) =>
        `  ${JSON.stringify(name)}: {\n    viewBox: '${data.viewBox}',\n    path: '${data.path}',\n  },`,
    )
    .join('\n');

  return `/*
 * Generated by scripts/extract-icons.ts — do not edit by hand.
 *
 * Run \`pnpm --filter @shape-and-flow/booking-ui icons\` to regenerate.
 * \`icon-paths.spec.ts\` fails if this file and the Font Awesome package disagree.
 *
 * Icons: Font Awesome Free, CC BY 4.0 — https://fontawesome.com/license/free
 */
export interface IconData {
  viewBox: string;
  path: string;
}

export const ICON_PATHS = {
${entries}
} as const satisfies Record<string, IconData>;

export type IconName = keyof typeof ICON_PATHS;
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const target = resolve(packageDir, '../src/icon-paths.ts');
  writeFileSync(target, render(buildAll()), 'utf8');
  process.stdout.write(`wrote ${String(Object.keys(WANTED).length)} icons to ${target}\n`);
}
